# Generated by Django 4.0.4 on 2022-07-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username_motivator'),
        ('users', '0002_motivation_alter_user_username'),
    ]

    operations = [
    ]
